[package]
name = "usls-doc"
version = "0.1.1"
rust-version = "1.82"
edition = "2021"
description = "A Rust library integrated with ONNXRuntime, providing a collection of ML models."
repository = "https://github.com/jamjamjon/usls"
authors = ["Jamjamjon <xxyydzml@outlook.com>"]
license = "MIT"
readme = "README.md"
exclude = ["assets/*", "examples/*", "runs/*", "benches/*"]

[dependencies]
aksr = { version = "0.0.2" }
image = { version = "0.25" }
imageproc = { version = "0.25" }
ndarray = { version = "0.16.1", features = ["rayon", "serde"] }
rayon = { version = "1.10.0" }
anyhow = { version = "1.0" }
regex = { version = "1.11.1" }
rand = { version = "0.8.5" }
chrono = { version = "0.4.30" }
tokenizers = { version = "0.21.0" }
log = { version = "0.4.22" }
indicatif = "0.17.8"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
ort = { version = "2.0.0-rc.9", features = ["cuda", "ndarray", "half"] }
prost = "0.12.6"
ab_glyph = "0.2.29"
tempfile = "3.19.1"
dirs = "6.0.0"
geo = "0.30.0"
natord = "1.0.9"
half = { version = "2.3.1" }
ureq = { version = "2.12.1", default-features = false, features = ["tls"] }
fast_image_resize = { version = "5.1.3", features = ["image"] }
sha2 = "0.10.8"
ndarray-npy = "0.9.1"
pdfium-render = "0.8.3" 

[dev-dependencies]
argh = "0.1.13"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }


[features]
default = [
    "ort/ndarray",
    "ort/copy-dylibs",
    "ort/load-dynamic",
    "ort/half",
]

auto = ["ort/download-binaries"]
cuda = ["ort/cuda"]
trt = ["ort/tensorrt"]
mps = ["ort/coreml"]

# Model-specific features (all optional, only yolo and svtr in default)
beit = []
blip = []
clip = []
convnext = []
d_fine = []
db = []
deim = []
deit = []
depth_anything = []
depth_pro = []
dinov2 = []
fast = []
fastvit = []
florence2 = []
grounding_dino = []
linknet = []
mobileone = []
modnet = []
moondream2 = []
owl = []
picodet = []
pipeline = []
rtdetr = []
rtmo = []
sam = []
sapiens = []
slanet = []
smolvlm = []
svtr = []
trocr = []
yolop = []
yolo = []

[profile.release]
lto = true
strip = true
panic = "abort"